### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by Olivierig** [gempesaw/Selenium-UserAgent#1]
Hi, I would be courious to try your code. How can I install it? I am using moonraker.

**Comment by gempesaw** [comment]
hmm, moonraker? What is that - is that this moonraker: https://github.com/LateRoomsGroup/moonraker ?

If so, you might have to choose a different project - this is a Perl project, and that moonraker project is NodeJS. While there are actually some projects combining Perl and Node, there's probably an easier way to accomplish your goal.

Speaking of, what are you trying to accomplish with moonraker ? :)
