### ISSUE TITLE
List::Util version 1.33 is required for List::Util::any

### ISSUE THREAD

**Issue by kcaran** [gempesaw/Selenium-UserAgent#3]
My install of Selenium::UserAgent failed because I was on version 1.25 of List::Util (Perl 5.16). The module uses List::Util::any which was introduced in 1.33.

I could do a pull request for this, but I don't want to cause you more work.

**Comment by gempesaw** [comment]
Oh! I didn't know that about `List::Util::any`. I'll go ahead and pin that minimum version requirement. 

Thanks!
